version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - /frontend/src/:/usr/app/src
      - /frontend/public/:/usr/app/public
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
      - /usr/app/node_modules
      - /frontend/src/:/usr/app/src
      - /frontend/public/:/usr/app/public
    command: ["npm", "run", "test"]